name: influencer_connect
description: "Kenya's Premier Influencer Marketing Platform - Connecting Brands with Creators"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Fonts
  google_fonts: ^6.1.0
  
  # HTTP & API
  http: ^1.1.0
  
  # Storage (for local data)
  shared_preferences: ^2.2.2
  
  # Routing
  go_router: ^12.1.3
  
  # Utilities
  intl: ^0.18.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add assets folder for images, icons, etc.
  assets:
    - assets/images/
    - assets/icons/
  
  # Add custom fonts if needed (optional since we're using Google Fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf